<?php

namespace wabel\PMBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LikeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LikeeRepository extends EntityRepository
{
}
